AWSTemplateFormatVersion: 2010-09-09
Description: >-
  emails-queue-api

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AccountId:
    Type: String
    Description: AWS account ID
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Mappings:
  EnvironmentMap:
    prod:
      bucket: emails-service-storage
      domain: emails-queue-api.bowland.link
      queue: emails-queue-service-SimpleQueue-1S70UGPUYHOUI.fifo
    test:
      bucket: emails-service-storage-test
      domain: emails-queue-api-test.bowland.link
      queue: emails-queue-service-test-SimpleQueue-1RVBFSJJJDFXF.fifo

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Auth:
        ApiKeyRequired: true # sets for all methods
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for emails-queue-api
      Domain:
        DomainName: !FindInMap [EnvironmentMap, !Ref Environment, domain]
        CertificateArn: !Sub 'arn:aws:acm:us-east-1:${AccountId}:certificate/7f4606f7-302c-40a8-ac9d-e63db9b7a712'
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: Z01312547RGU1BYKIJXY
        BasePath:
          - /v1

  PostItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/post-item.postItem
      CodeUri: './dist'
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 30
      Description: Adds emails to the queue to be sent.
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        # Grant access to S3 bucket
        - S3WritePolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, bucket]
        # Grant access to SQS queue
        - SQSSendMessagePolicy:
            QueueName: !FindInMap [EnvironmentMap, !Ref Environment, queue]
      Environment:
        Variables:
          EMAIL_BUCKET: !FindInMap [EnvironmentMap, !Ref Environment, bucket]
          EMAIL_REGION: us-east-1
          SQS_MESSAGE_QUEUE_ID: emails
          SQS_QUEUE_URL: !Sub
            - 'https://sqs.us-east-1.amazonaws.com/${AccountId}/${Queue}'
            - Queue: !FindInMap [EnvironmentMap, !Ref Environment, queue]
      Events:
        ApiKey:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /emails
            Method: post
            Auth:
              ApiKeyRequired: true

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [PostItemFunction]
    Properties:
      LogGroupName: !Sub /aws/lambda/${PostItemFunction}
      RetentionInDays: 30
